### ISSUE TITLE
Other missing links discussion

### ISSUE THREAD

**Issue by jdeniau** [1up-lab/OneupAclBundle#11]
Hi, 

I started to develop two missing features of Symfony and your bundle on [another bundle](https://github.com/mapado/acl-bundle).

But as your bundle does what it does great, and I need those functionnality too, I was telling myself that I should just PR your bundle with my functionnalities.

The two features I added are: 
- Grant/revoke access to an object in command line 
- Access all objects for a specific user (today symfony propose only the reverse side, ie, Access all users for a specific object).

Tell me if you are interested and I will PR you as soon as possible.

Julien

**Comment by bytehead** [comment]
@jdeniau Is this still relevant?
