### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by helmuthva** [1up-lab/OneupAclBundle#36]
Any plans to provide a version compatible with Symfony ^3.0 in the near future?

**Comment by bytehead** [comment]
Hi @helmuthva 
So far not. Also see #30, but you're welcome to provide a PR :)

**Comment by bytehead** [comment]
Ah, there is already a PR #33. See the branch as well: https://github.com/1up-lab/OneupAclBundle/tree/feature/symfony3

**Comment by bytehead** [comment]
See #33 - is ready to merge.
